repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace
        exclude_types: [markdown]
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files

  - repo: https://github.com/tekwizely/pre-commit-golang
    rev: v1.0.0-rc.1
    hooks:
      - id: go-imports
        args:
          - "-local"
          - "github.com/ColoradoSchoolOfMines/mineshspc.com"
          - "-w"
        exclude: _templ\.go$
      - id: go-vet-mod
      - id: go-staticcheck-mod
