// Code generated by templ - DO NOT EDIT.

// templ: version: v0.2.696
package templates

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import (
	"bytes"
	"context"
	"io"

	"github.com/a-h/templ"
)

func Register() templ.Component {
	return templ.ComponentFunc(func(ctx context.Context, templ_7745c5c3_W io.Writer) (templ_7745c5c3_Err error) {
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templ_7745c5c3_W.(*bytes.Buffer)
		if !templ_7745c5c3_IsBuffer {
			templ_7745c5c3_Buffer = templ.GetBuffer()
			defer templ.ReleaseBuffer(templ_7745c5c3_Buffer)
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<div class=\"container\"><div class=\"row page-header\"><div class=\"col\"><h1>Register</h1></div></div></div><div class=\"container page-content register\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if !RegistrationEnabled(ctx) {
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<div class=\"row p-4\"><div class=\"col\"><div class=\"alert alert-warning\" role=\"alert\">Registration is currently disabled. Check back soon!</div></div></div>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<div class=\"row p-4\"><div class=\"col lg-5\"><p>Please note that the registration deadline is for filling out teams. You can sign forms past the registration deadline.</p><ol class=\"register-flow mb-0\"><li><span class=\"register-item\">1</span> <span class=\"register-text-header\"><b>Teachers</b> register students.</span><div class=\"register-text p-4\"><p><b>Teachers must register teams for the competition.</b> You may register as many teams as you would like, however, we only guarantee that two teams per-school will be able to participate in-person.</p><p>All registrations are subject to approval by the HSPC organizers.</p>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if RegistrationEnabled(ctx) {
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<a href=\"/register/teacher/createaccount\" type=\"button\" class=\"btn btn-primary\">Register A Team</a>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("</div></li><li class=\"pt-4\"><span class=\"register-item\">2</span> <span class=\"register-text-header\"><b>Students</b> confirm your email.</span><div class=\"register-text p-4\"><p><b>Students need to be signed up by their teachers.</b> You should recieve an email once your teacher has signed you up.</p><p class=\"mb-0\">We need to verify your email address is correct so that we can create your account on Kattis.</p></div></li><li class=\"pt-4\"><span class=\"register-item\">3</span> <span class=\"register-text-header\"><b>Parents/guardians</b> sign participation forms.</span><div class=\"register-text p-4\"><p><b>Students need to be signed up by their teachers.</b> After your student has been signed up, you may need to sign additional forms in order for your student to be allowed to participate.</p><p class=\"mb-0\">If your student is not a minor, they may sign the forms for themselves.</p></div></li></ol></div></div></div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if !templ_7745c5c3_IsBuffer {
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteTo(templ_7745c5c3_W)
		}
		return templ_7745c5c3_Err
	})
}
