// Code generated by templ - DO NOT EDIT.

// templ: version: v0.2.696
package templates

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import (
	"bytes"
	"context"
	"io"

	"github.com/a-h/templ"
)

func Rules() templ.Component {
	return templ.ComponentFunc(func(ctx context.Context, templ_7745c5c3_W io.Writer) (templ_7745c5c3_Err error) {
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templ_7745c5c3_W.(*bytes.Buffer)
		if !templ_7745c5c3_IsBuffer {
			templ_7745c5c3_Buffer = templ.GetBuffer()
			defer templ.ReleaseBuffer(templ_7745c5c3_Buffer)
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<div class=\"container\"><div class=\"row page-header\"><div class=\"col\"><h1>Competition Rules</h1></div></div></div><div class=\"container page-content rules\"><div class=\"row\"><div class=\"col m-4\"><h2>Teams</h2><p>Teams must have a minimum of two students and a maximum of four students. <b>Teams must have a faculty sponsor.</b> If your school does not have a faculty sponsor, please <a href=\"mailto:support@mineshspc.com\">email us</a>.</p><p>Teams can be made up of students from different schools as long as all students and faculty sponsors agree.</p><h2>Internet Access &amp; Code Generation</h2><p>This competition is <b>open-internet</b>. You may use the internet for looking up language documentation or researching algorithms. You may <b>not</b> use interactive online services such as chat rooms or forums to communicate with anyone during the competition. You may <b>not</b> communicate with anyone outside of your team.</p><p>The problems are written specifically for the competition, so looking up the problems will not be useful. Additionally, the teams that do the best in the competition generally do not use the internet extensively during the competition because they already are familiar with their language&#39;s standard library and know a variety of algorithms that may be used to solve the problems.</p><p><b>Third party code generation is not allowed.</b> Any team that uses code generation AI/LLMs will be immediately disqualified and their school will be ineligible from participating in HSPC in future years. All solutions will be reviewed for AI use. We reserve the right to ask teams to explain the solution in detail to judges and revoke credit for solutions if the judges feel the team does not provide an adequate explanation.</p><h2 id=\"bringing-own-tech\">Bringing Your Own Technology</h2><p>In-person teams will be <b>provided a single computer</b> ")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var2 string
		templ_7745c5c3_Var2, templ_7745c5c3_Err = templ.JoinStringErrs(`for`)
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `internal/templates/rules.templ`, Line: 48, Col: 70}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var2))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(" the competition. Teams may not use more than one Mines-provided computer. Teams <b>are allowed to bring and use additional computers</b> ")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var3 string
		templ_7745c5c3_Var3, templ_7745c5c3_Err = templ.JoinStringErrs(`if`)
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `internal/templates/rules.templ`, Line: 53, Col: 16}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var3))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(" they wish.</p><p>Using the computer provided is often an effective strategy as it allows team members to collaborate on solutions rather than having to work on their own.</p><h2>In-Person Prizes</h2><p>In-person teams can win prizes by placing in the top three. We also may award prizes for fun &amp; creative solutions or quick completion of problems.</p><ul><li>Prize for each person in the first place team</li><li>Prize for each person in the second place team</li><li>Prize for each person in the third place team</li></ul><p>Rules and prizes are subject to change.</p></div></div></div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if !templ_7745c5c3_IsBuffer {
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteTo(templ_7745c5c3_W)
		}
		return templ_7745c5c3_Err
	})
}
