// Code generated by templ - DO NOT EDIT.

// templ: version: v0.2.696
package partials

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import (
	"bytes"
	"context"
	"html/template"
	"io"

	"github.com/a-h/templ"

	"github.com/ColoradoSchoolOfMines/mineshspc.com/internal/contextkeys"
)

func GetHostedByHTML(ctx context.Context) template.HTML {
	hostedByHTML, _ := ctx.Value(contextkeys.ContextKeyHostedByHTML).(template.HTML)
	return hostedByHTML
}

func Footer() templ.Component {
	return templ.ComponentFunc(func(ctx context.Context, templ_7745c5c3_W io.Writer) (templ_7745c5c3_Err error) {
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templ_7745c5c3_W.(*bytes.Buffer)
		if !templ_7745c5c3_IsBuffer {
			templ_7745c5c3_Buffer = templ.GetBuffer()
			defer templ.ReleaseBuffer(templ_7745c5c3_Buffer)
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<footer class=\"footer mt-4 pt-4 ps-4 pe-4\"><div class=\"row\"><div class=\"col text-center text-secondary\"><p>Organized by <a href=\"https://acm.mines.edu\" target=\"_blank\"><img class=\"img-fluid acm-logo\" src=\"/static/acm.png\" alt=\"Mines ACM\"></a> <span class=\"hosted-at\">and hosted at</span> <a href=\"https://www.mines.edu\" target=\"_blank\"><img class=\"img-fluid mines-logo\" src=\"/static/mines.png\" alt=\"Colorado School of Mines\"></a></p><p class=\"small\">Need help? You can always <a href=\"mailto:support@mineshspc.com\">email support</a> with any questions you have.</p><p class=\"small\">&copy; 2023 Mines ACM. View the <a href=\"https://github.com/ColoradoSchoolOfMines/mineshspc.com\" target=\"_blank\">source code</a>.")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templ.Raw(GetHostedByHTML(ctx)).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("</p></div></div></footer>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if !templ_7745c5c3_IsBuffer {
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteTo(templ_7745c5c3_W)
		}
		return templ_7745c5c3_Err
	})
}
